# Numpy

In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
b=np.array([1,2,3,4])
b=b**2
print(b)

[ 1  4  9 16]


In [9]:
a1=np.array([1,2,3,4])
b1=np.array([1,2,3,4])
c1=a1*b1
print(c1)

[ 1  4  9 16]


# 2 dimentioanl array

In [10]:
a2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(a1.shape)
print(a2.shape)

(4,)
(3, 4)


In [12]:
### Now lets try to print some specific numers from the a2 array lets say we only want to print 2,3 / 6,7 / 10,11 at the manner of dimentional array
print(a2[0:,1:3])

### print(a2[staring row index:endind row index+1 , starting coloumn index: ending column index+1])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [13]:
### How to define an array of 0

zero=np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
### How to define an array of 1

ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
### How to create an array with start and end point

arrange=np.arange(1,10,1) ### np.arange(start,stop,step)
print(arrange)

[1 2 3 4 5 6 7 8 9]


In [39]:
### It is used to create a number of element between start and ending value

lin = np.linspace(0, 100000, 100)  # Start, Stop, Number of values

print(lin)

[     0.           1010.1010101    2020.2020202    3030.3030303
   4040.4040404    5050.50505051   6060.60606061   7070.70707071
   8080.80808081   9090.90909091  10101.01010101  11111.11111111
  12121.21212121  13131.31313131  14141.41414141  15151.51515152
  16161.61616162  17171.71717172  18181.81818182  19191.91919192
  20202.02020202  21212.12121212  22222.22222222  23232.32323232
  24242.42424242  25252.52525253  26262.62626263  27272.72727273
  28282.82828283  29292.92929293  30303.03030303  31313.13131313
  32323.23232323  33333.33333333  34343.43434343  35353.53535354
  36363.63636364  37373.73737374  38383.83838384  39393.93939394
  40404.04040404  41414.14141414  42424.24242424  43434.34343434
  44444.44444444  45454.54545455  46464.64646465  47474.74747475
  48484.84848485  49494.94949495  50505.05050505  51515.15151515
  52525.25252525  53535.35353535  54545.45454545  55555.55555556
  56565.65656566  57575.75757576  58585.85858586  59595.95959596
  60606.06060606  61616.16

In [41]:
a2.ndim


2